version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:7.17.6
    container_name: zio-elasticsearch-example
    ports:
      - "9200:9200"
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
