version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.12.0
    container_name: zio-elasticsearch-8-test
    ports:
      - "9200:9200"
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
