addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"   % "0.14.6")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"  % "0.13.1")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.11.2")
addSbtPlugin("com.github.sbt" % "sbt-unidoc"     % "0.6.1")
addSbtPlugin("com.github.sbt" % "sbt-header"     % "5.11.0")
addSbtPlugin("io.spray"       % "sbt-revolver"   % "0.10.0")
addSbtPlugin("org.scalameta"  % "sbt-mdoc"       % "2.8.2")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"   % "2.5.6")
