addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"   % "0.12.1")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"  % "0.12.0")
addSbtPlugin("com.github.sbt"    % "sbt-ci-release" % "1.6.1")
addSbtPlugin("com.github.sbt"    % "sbt-unidoc"     % "0.5.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"     % "5.10.0")
addSbtPlugin("io.spray"          % "sbt-revolver"   % "0.10.0")
addSbtPlugin("org.scalameta"     % "sbt-mdoc"       % "2.5.4")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"   % "2.5.2")
