module.exports = {
    about_sidebar:
        [
            'about/about_index',
            'about/about_contributing',
            'about/about_code_of_conduct'
        ],
    overview_sidebar:
        [
            'overview/overview_index',
            'overview/overview_installation',
            'overview/overview_usage',
            'overview/overview_elastic_query',
            'overview/overview_elastic_aggregation',
            'overview/overview_elastic_request',
            'overview/overview_zio_prelude_schema',
            'overview/overview_elastic_executor',
            'overview/overview_fluent_api',
            'overview/overview_bulkable',
            'overview/overview_streaming',
        ]
}
