module.exports = {
  about_sidebar:
    [
      'about/about_index',
      'about/about_contributing',
      'about/about_code_of_conduct'
    ],
  overview_sidebar:
    [
      'overview/overview_index',
      'overview/overview_usage',
      'overview/overview_fluent_api',
      'overview/overview_bulkable',
      'overview/overview_zio_prelude_schema',
      'overview/overview_streaming',
      'overview/overview_elastic_query',
      'overview/overview_elastic_request',
      'overview/overview_elastic_executor',
    ]
}
